// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADO_LVuYvLekJw7Mmuepd1RVO4-EnF94Y',
    appId: '1:176894846158:web:96b4edacff78edfa8c9c9f',
    messagingSenderId: '176894846158',
    projectId: 'collabdev-b911c',
    authDomain: 'collabdev-b911c.firebaseapp.com',
    databaseURL: 'https://collabdev-b911c-default-rtdb.firebaseio.com',
    storageBucket: 'collabdev-b911c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iFBm9c1wBv4ox_QUR1HjSVk7mQ7Fabc',
    appId: '1:176894846158:android:aa6c2d337e302e008c9c9f',
    messagingSenderId: '176894846158',
    projectId: 'collabdev-b911c',
    databaseURL: 'https://collabdev-b911c-default-rtdb.firebaseio.com',
    storageBucket: 'collabdev-b911c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9zZw65-Spu_YQbhiJ56guRIOTWpD9L0',
    appId: '1:176894846158:ios:96efda523ff10cb18c9c9f',
    messagingSenderId: '176894846158',
    projectId: 'collabdev-b911c',
    databaseURL: 'https://collabdev-b911c-default-rtdb.firebaseio.com',
    storageBucket: 'collabdev-b911c.firebasestorage.app',
    iosClientId: '176894846158-m44d9qmhafrt9vqmvul3d1fvf5klc6du.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9zZw65-Spu_YQbhiJ56guRIOTWpD9L0',
    appId: '1:176894846158:ios:96efda523ff10cb18c9c9f',
    messagingSenderId: '176894846158',
    projectId: 'collabdev-b911c',
    databaseURL: 'https://collabdev-b911c-default-rtdb.firebaseio.com',
    storageBucket: 'collabdev-b911c.firebasestorage.app',
    iosClientId: '176894846158-m44d9qmhafrt9vqmvul3d1fvf5klc6du.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADO_LVuYvLekJw7Mmuepd1RVO4-EnF94Y',
    appId: '1:176894846158:web:ecb4452069e276818c9c9f',
    messagingSenderId: '176894846158',
    projectId: 'collabdev-b911c',
    authDomain: 'collabdev-b911c.firebaseapp.com',
    databaseURL: 'https://collabdev-b911c-default-rtdb.firebaseio.com',
    storageBucket: 'collabdev-b911c.firebasestorage.app',
  );

}