
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { DialogsProvider } from "@/context/DialogsContext";
import { MatrixProvider } from "@/context/matrixContext";
import { ThreadProvider } from "@/context/ThreadContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-new-gr-c-s-check-loaded="14.1215.0"
      data-gr-ext-installed="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MatrixProvider>
          <ThreadProvider>
            <DialogsProvider>
              <AuthProvider>
                {children}
              </AuthProvider>
            </DialogsProvider>
          </ThreadProvider>
        </MatrixProvider>
      </body>
    </html>
  );
}
